Add probabilistic precipitation forecasts
orcestra-campaign/weather pull request #221
Opened 2024-09-14 20:58 UTC by HF7weatherman

This MR adds the probabilistic forecast of 3-hourly precipitation to the weather briefing in the "Supporting Figures" section. For an example figure see below. The briefing still generates without any problems after including these changes.

![precip_enfo1](https://github.com/user-attachments/assets/f4349266-51a2-4e28-bdb3-3f7374cea1d4)

2024-09-16 14:06 UTC, HF7weatherman commented
@Lucalino @sortega87 Just a quick reminder asking for your revision of this MR 😉

2024-09-16 20:01 UTC, sortega87 commented
> @Lucalino @sortega87 Just a quick reminder asking for your revision of this MR 😉

Hi @HF7weatherman! Thanks for the reminder, I had missed it somehow. Looks good to me and can be merge after addressing my title comment above. Thanks for implementing the plots :)

2024-09-16 20:01 UTC, sortega87 requested changes

2024-09-19 13:33 UTC, HF7weatherman commented on src/wblib/template.qmd
> +### Horizontal sfc. wind conv. & Prob. precip. forecast
On this slide I would show both, surface convergence and the probabilistic precip forecast for lead times `+108h` and `+132h`. Thus, I would leave the header as is.

2024-09-19 14:20 UTC, sortega87 commented on src/wblib/template.qmd
> +### Horizontal sfc. wind conv. & Prob. precip. forecast
Sounds good. Thanks Henning!

2024-09-19 14:20 UTC, sortega87 approved these changes
Looks good! Thanks Henning!

2024-09-19 14:44 UTC, merged